// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef _DISPENSER_UI_H
#define _DISPENSER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_SC00Registrar.h"
#include "ui_SC01Pulsera.h"
#include "ui_SC02Selection.h"
#include "ui_SC03Dispensar.h"
#include "ui_SC04Finalizar.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_naos_oscuro_h_png);   // assets/Naos_Oscuro_h.png
LV_IMG_DECLARE( ui_img_wristband_green_png);   // assets/wristband_green.png
LV_IMG_DECLARE( ui_img_rfid_png);   // assets/rfid.png
LV_IMG_DECLARE( ui_img_naos_claro_h_png);   // assets/Naos_Claro_h.png
LV_IMG_DECLARE( ui_img_beer_mug_png);   // assets/beer_mug.png
LV_IMG_DECLARE( ui_img_cocktail_png);   // assets/cocktail.png
LV_IMG_DECLARE( ui_img_red_wine_png);   // assets/red_wine.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
