// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

// COMPONENT SelectBasic

lv_obj_t *ui_SelectBasic_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_SelectBasic;
cui_SelectBasic = lv_obj_create(comp_parent);
lv_obj_set_width( cui_SelectBasic, 159);
lv_obj_set_height( cui_SelectBasic, 154);
lv_obj_set_x( cui_SelectBasic, -265 );
lv_obj_set_y( cui_SelectBasic, -104 );
lv_obj_set_align( cui_SelectBasic, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_SelectBasic, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_SelectBasic, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_SelectBasic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_SelectBasic, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_SelectBasic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_SelectBasic, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_SelectBasic, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_SelectBasic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(cui_SelectBasic, 0, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_border_color(cui_SelectBasic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_border_opa(cui_SelectBasic, 0, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_radius(cui_SelectBasic, 30, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_color(cui_SelectBasic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_opa(cui_SelectBasic, 0, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_border_color(cui_SelectBasic, lv_color_hex(0x221BB1), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_border_opa(cui_SelectBasic, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_border_width(cui_SelectBasic, 3, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_shadow_color(cui_SelectBasic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_shadow_opa(cui_SelectBasic, 255, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_set_style_clip_corner(cui_SelectBasic, true, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

lv_obj_t *cui_ImgSelection;
cui_ImgSelection = lv_image_create(cui_SelectBasic);
lv_obj_set_width( cui_ImgSelection, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ImgSelection, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_ImgSelection, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ImgSelection,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ImgSelection, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( cui_ImgSelection, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( cui_ImgSelection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(cui_ImgSelection,230);
lv_obj_set_style_blend_mode(cui_ImgSelection, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SELECTBASIC_NUM);
children[UI_COMP_SELECTBASIC_SELECTBASIC] = cui_SelectBasic;
children[UI_COMP_SELECTBASIC_IMGSELECTION] = cui_ImgSelection;
lv_obj_add_event_cb(cui_SelectBasic, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_SelectBasic, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_SelectBasic_create_hook(cui_SelectBasic);
return cui_SelectBasic; 
}

