// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef _UI_COMP_SELECTBASIC_H
#define _UI_COMP_SELECTBASIC_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SelectBasic
#define UI_COMP_SELECTBASIC_SELECTBASIC 0
#define UI_COMP_SELECTBASIC_IMGSELECTION 1
#define _UI_COMP_SELECTBASIC_NUM 2
lv_obj_t *ui_SelectBasic_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
