// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

void ui_comp_BtnNextComp_create_hook( lv_obj_t * comp)
{
}

void ui_comp_SelectBasic_create_hook( lv_obj_t * comp)
{
}
