// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

// COMPONENT BtnNextComp

lv_obj_t *ui_BtnNextComp_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_BtnNextComp;
cui_BtnNextComp = lv_button_create(comp_parent);
lv_obj_set_width( cui_BtnNextComp, 51);
lv_obj_set_height( cui_BtnNextComp, 31);
lv_obj_set_x( cui_BtnNextComp, 326 );
lv_obj_set_y( cui_BtnNextComp, 197 );
lv_obj_set_align( cui_BtnNextComp, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_BtnNextComp, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( cui_BtnNextComp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(cui_BtnNextComp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ColorBtn);
ui_object_set_themeable_style_property(cui_BtnNextComp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ColorBtn);
lv_obj_set_style_clip_corner(cui_BtnNextComp, true, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label5;
cui_Label5 = lv_label_create(cui_BtnNextComp);
lv_obj_set_width( cui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label5,"Next");

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BTNNEXTCOMP_NUM);
children[UI_COMP_BTNNEXTCOMP_BTNNEXTCOMP] = cui_BtnNextComp;
children[UI_COMP_BTNNEXTCOMP_LABEL5] = cui_Label5;
lv_obj_add_event_cb(cui_BtnNextComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_BtnNextComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_BtnNextComp_create_hook(cui_BtnNextComp);
return cui_BtnNextComp; 
}

