// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef UI_SC00REGISTRAR_H
#define UI_SC00REGISTRAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SC00Registrar
extern void ui_SC00Registrar_screen_init(void);
extern void ui_SC00Registrar_screen_destroy(void);
extern lv_obj_t *ui_SC00Registrar;
extern lv_obj_t *ui_LabelId;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

