// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

lv_obj_t *ui_SC00Registrar = NULL;lv_obj_t *ui_LabelId = NULL;
// event funtions

// build funtions

void ui_SC00Registrar_screen_init(void)
{
ui_SC00Registrar = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SC00Registrar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SC00Registrar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ColorBgr);
ui_object_set_themeable_style_property(ui_SC00Registrar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ColorBgr);

ui_LabelId = lv_label_create(ui_SC00Registrar);
lv_obj_set_width( ui_LabelId, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelId, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelId, -8 );
lv_obj_set_y( ui_LabelId, -40 );
lv_obj_set_align( ui_LabelId, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelId,"Dispenser ID");
ui_object_set_themeable_style_property(ui_LabelId, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_ColorTxt);
ui_object_set_themeable_style_property(ui_LabelId, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_ColorTxt);
lv_obj_set_style_text_font(ui_LabelId, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_SC00Registrar_screen_destroy(void)
{
   if (ui_SC00Registrar) lv_obj_del(ui_SC00Registrar);

// NULL screen variables
ui_SC00Registrar= NULL;
ui_LabelId= NULL;

}
