// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef UI_SC02SELECTION_H
#define UI_SC02SELECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SC02Selection
extern void ui_SC02Selection_screen_init(void);
extern void ui_SC02Selection_screen_destroy(void);
extern lv_obj_t *ui_SC02Selection;
extern lv_obj_t *ui_SC02Title;
extern lv_obj_t *ui_ContOptions;
extern lv_obj_t *ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

