// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef UI_SC01PULSERA_H
#define UI_SC01PULSERA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SC01Pulsera
extern void ui_SC01Pulsera_screen_init(void);
extern void ui_SC01Pulsera_screen_destroy(void);
extern void ui_event_SC01Pulsera( lv_event_t * e);
extern lv_obj_t *ui_SC01Pulsera;
extern lv_obj_t *ui_TitleScreen01;
extern lv_obj_t *ui_BrdScan;
extern lv_obj_t *ui_LblErrorMessage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

