// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

lv_obj_t *ui_SC02Selection = NULL;lv_obj_t *ui_SC02Title = NULL;lv_obj_t *ui_ContScrollOption = NULL;
// event funtions

// build funtions

void ui_SC02Selection_screen_init(void)
{
ui_SC02Selection = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SC02Selection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SC02Selection, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ColorBgr);
ui_object_set_themeable_style_property(ui_SC02Selection, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ColorBgr);

ui_SC02Title = lv_label_create(ui_SC02Selection);
lv_obj_set_width( ui_SC02Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SC02Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SC02Title, 6 );
lv_obj_set_y( ui_SC02Title, -202 );
lv_obj_set_align( ui_SC02Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_SC02Title,"Selecciona tu Bebida");
ui_object_set_themeable_style_property(ui_SC02Title, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_ColorTxt);
ui_object_set_themeable_style_property(ui_SC02Title, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_ColorTxt);
lv_obj_set_style_text_font(ui_SC02Title, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SC02Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_SC02Title, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_USER_1);

ui_ContScrollOption = lv_obj_create(ui_SC02Selection);
lv_obj_remove_style_all(ui_ContScrollOption);
lv_obj_set_width( ui_ContScrollOption, 794);
lv_obj_set_height( ui_ContScrollOption, 399);
lv_obj_set_x( ui_ContScrollOption, 0 );
lv_obj_set_y( ui_ContScrollOption, 24 );
lv_obj_set_align( ui_ContScrollOption, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_ContScrollOption,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContScrollOption, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_ContScrollOption, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_ContScrollOption, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_ContScrollOption, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_ContScrollOption, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_pad_row(ui_ContScrollOption, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_ContScrollOption, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_SC02Selection_screen_destroy(void)
{
   if (ui_SC02Selection) lv_obj_del(ui_SC02Selection);

// NULL screen variables
ui_SC02Selection= NULL;
ui_SC02Title= NULL;
ui_ContScrollOption= NULL;

}
