// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef UI_SC04FINALIZAR_H
#define UI_SC04FINALIZAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SC04Finalizar
extern void ui_SC04Finalizar_screen_init(void);
extern void ui_SC04Finalizar_screen_destroy(void);
extern lv_obj_t *ui_SC04Finalizar;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

