// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef UI_SC03DISPENSAR_H
#define UI_SC03DISPENSAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SC03Dispensar
extern void ui_SC03Dispensar_screen_init(void);
extern void ui_SC03Dispensar_screen_destroy(void);
extern lv_obj_t *ui_SC03Dispensar;
extern lv_obj_t *ui_SC03Title;
//extern lv_obj_t *ui_Spinbox1;
extern lv_obj_t *ui_BarDispensed;
extern lv_obj_t *ui_ImageBeverage;
extern lv_obj_t *ui_BtnFinalizr1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

