// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_COLORBTN 0
#define UI_THEME_COLOR_COLORTXT 1
#define UI_THEME_COLOR_COLORBGR 2
#define UI_THEME_COLOR_COLORWIN 3
#define UI_THEME_COLOR_COLORBER 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_ColorBtn[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorBtn[1];

extern const ui_theme_variable_t _ui_theme_color_ColorTxt[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorTxt[1];

extern const ui_theme_variable_t _ui_theme_color_ColorBgr[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorBgr[1];

extern const ui_theme_variable_t _ui_theme_color_ColorWin[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorWin[1];

extern const ui_theme_variable_t _ui_theme_color_ColorBer[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColorBer[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
