// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Dispenser

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_ColorBtn[1] = {0x201C20};
const ui_theme_variable_t _ui_theme_alpha_ColorBtn[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorTxt[1] = {0xE5E6E5};
const ui_theme_variable_t _ui_theme_alpha_ColorTxt[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorBgr[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_ColorBgr[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorWin[1] = {0x680044};
const ui_theme_variable_t _ui_theme_alpha_ColorWin[1] = {255};

const ui_theme_variable_t _ui_theme_color_ColorBer[1] = {0xBC8208};
const ui_theme_variable_t _ui_theme_alpha_ColorBer[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

